# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

r_github_packages:
  - vimc/orderly@i2517
  - vimc/orderly.server@i2517

addons:
  apt:
    packages:
      - libapparmor-dev
