# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

r_github_packages:
  - vimc/orderly@i1795
  - vimc/orderly.server

addons:
  apt:
    packages:
      - libapparmor-dev

r_check_args: --no-vignettes
