#!/usr/bin/env bash
set -e

HERE=$(dirname $0)
. $HERE/common

PACKAGE_ROOT=$(realpath $HERE/..)
docker build \
       --tag $APP_DOCKER_COMMIT_TAG \
       --tag $APP_DOCKER_BRANCH_TAG \
       -f docker/Dockerfile $PACKAGE_ROOT
